import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Reuben",
  description: "Terms of service for Reuben Inc. and the Reux ecosystem.",
};

export default function TermsPage() {
  return (
    <div className="pt-32 pb-24 min-h-screen">
      <div className="container mx-auto px-4 md:px-8 max-w-3xl">
        <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
        <p className="text-gray-400 mb-8">Last updated: May 2026</p>

        <div className="prose prose-invert prose-gray max-w-none space-y-6 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Acceptance</h2>
            <p>
              By accessing the Reuben website or using the Business Simulator demo, you agree to these terms. If you do not agree, please do not use the site.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Demo Use</h2>
            <p>
              The Business Simulator is a public demo provided for evaluation and exploration purposes. It is not intended to replace professional business analysis or financial advice.
            </p>
            <ul className="list-disc pl-5 space-y-2 text-gray-400 mt-3">
              <li>Simulation results are generated by a prototype engine and may not reflect real-world outcomes.</li>
              <li>Scenario data submitted to the simulator is processed in-session and is not permanently stored.</li>
              <li>The simulator is provided &quot;as is&quot; without warranty of any kind.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Intellectual Property</h2>
            <p>
              The Reuben name, Reux language, PLOS concept, website design, and all associated content are the intellectual property of Reuben Inc. You may not reproduce, distribute, or create derivative works from this content without written permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Limitation of Liability</h2>
            <p>
              Reuben Inc. is not liable for any decisions made based on simulator results or information presented on this website. The tools provided are for demonstration and educational purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Changes</h2>
            <p>
              We may update these terms at any time. Continued use of the site constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Contact</h2>
            <p>
              Questions about these terms can be sent to{" "}
              <a href="mailto:legal@reuben.inc" className="text-[#00F0FF] hover:underline">legal@reuben.inc</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
