export const SIMULATION_LIMITS = {
  MAX_RUN_SCENARIOS: 8,
  MAX_COMPARE_SCENARIOS: 12,
  MAX_FORECAST_PERIODS: 52,
  MAX_TIMELINE_POINTS: 52,
  MAX_SCENARIO_ID_LENGTH: 64,
  MAX_SCENARIO_NAME_LENGTH: 120,
  MAX_SCENARIO_DESCRIPTION_LENGTH: 500,
  SCENARIO_ID_REGEX: /^[a-zA-Z0-9][a-zA-Z0-9_-]*$/,
};
