import type { Simulation } from "./types";

// ─── Export Utilities ────────────────────────────────────────────────────────
// Utilities for exporting simulation results as CSV data or PDF reports.

function formatCurrency(val: number): string {
  return `$${val.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

function formatPercent(val: number): string {
  return `${val.toFixed(1)}%`;
}

function filenameFor(simulation: Simulation, extension: string): string {
  return `${simulation.name.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_report.${extension}`;
}

function downloadTextFile(filename: string, content: string, type: string): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

/**
 * Export simulation metrics as a CSV file.
 */
export function exportToCsv(simulation: Simulation): void {
  const rows: string[] = [];
  
  // Header row
  rows.push(["Scenario Name", "Role", "Employees", "Hourly Cost", "Weekly Demand", "Productivity (u/e/w)", "Margin", "Margin %", "Risk Score", "Workforce Load"].join(","));
  
  // Data rows
  simulation.scenarios.forEach((s, index) => {
    const isBaseline = index === 0 || s.id === simulation.comparison?.baseline.id;
    const role = isBaseline ? "Baseline" : "Alternative";
    const i = s.inputs;
    const r = s.summary;
    
    const row = [
      `"${i.name}"`,
      role,
      i.employees,
      `$${i.avgHourlyCost}`,
      i.weeklyDemand,
      r.productivity.toFixed(1),
      r.margin,
      r.marginPct,
      r.riskScore,
      r.workforceLoad,
    ];
    
    rows.push(row.join(","));
  });

  const csvContent = rows.join("\n");
  downloadTextFile(filenameFor(simulation, "csv"), csvContent, "text/csv;charset=utf-8;");
}

/**
 * Open a print-ready report that the browser can save as PDF.
 */
export function exportToPdf(simulation: Simulation): void {
  const recommendation = simulation.comparison?.recommendationReason
    ? `<section><h2>Reux Recommendation</h2><p>${escapeHtml(simulation.comparison.recommendationReason)}</p></section>`
    : "";
  const rows = simulation.scenarios.map((scenario) => {
    const isRecommended = simulation.comparison?.recommendedId === scenario.id;
    return `<tr>
      <td>${isRecommended ? "* " : ""}${escapeHtml(scenario.inputs.name)}</td>
      <td>${formatCurrency(scenario.summary.margin)}</td>
      <td>${formatPercent(scenario.summary.marginPct)}</td>
      <td>${scenario.summary.riskScore}/100</td>
      <td>${formatPercent(scenario.summary.workforceLoad)}</td>
      <td>${scenario.summary.productivity} u/e/w</td>
    </tr>`;
  }).join("");
  const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(simulation.name)} report</title>
  <style>
    body { font-family: Arial, sans-serif; color: #111827; margin: 32px; }
    h1 { margin-bottom: 4px; }
    .meta { color: #6b7280; margin-bottom: 24px; }
    table { border-collapse: collapse; width: 100%; margin-top: 16px; }
    th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; }
    th { background: #111827; color: white; }
  </style>
</head>
<body>
  <h1>Simulation Report: ${escapeHtml(simulation.name)}</h1>
  <div class="meta">Generated by Reux Business Simulator | ${new Date().toLocaleDateString()}</div>
  ${recommendation}
  <table>
    <thead>
      <tr>
        <th>Scenario</th>
        <th>Weekly Margin</th>
        <th>Margin %</th>
        <th>Risk Score</th>
        <th>Workforce Load</th>
        <th>Productivity</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <script>window.print();</script>
</body>
</html>`;
  const report = window.open("", "_blank", "noopener,noreferrer");
  if (report) {
    report.document.write(html);
    report.document.close();
    return;
  }

  downloadTextFile(filenameFor(simulation, "html"), html, "text/html;charset=utf-8;");
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
