import type { Simulation, ScenarioResult } from "./types";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ─── Export Utilities ────────────────────────────────────────────────────────
// Utilities for exporting simulation results as CSV data or PDF reports.

function formatCurrency(val: number): string {
  return `$${val.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

function formatPercent(val: number): string {
  return `${val.toFixed(1)}%`;
}

/**
 * Export simulation metrics as a CSV file.
 */
export function exportToCsv(simulation: Simulation): void {
  const rows: string[] = [];
  
  // Header row
  rows.push(["Scenario Name", "Role", "Employees", "Hourly Cost", "Weekly Demand", "Productivity (u/e/w)", "Margin", "Margin %", "Risk Score", "Workforce Load"].join(","));
  
  // Data rows
  simulation.scenarios.forEach((s) => {
    const isBaseline = s.id === simulation.baselineInputs.id;
    const role = isBaseline ? "Baseline" : "Alternative";
    const i = s.inputs;
    const r = s.summary;
    
    const row = [
      `"${i.name}"`,
      role,
      i.employees,
      `$${i.avgHourlyCost}`,
      i.weeklyDemand,
      r.productivity.toFixed(1),
      r.margin,
      r.marginPct,
      r.riskScore,
      r.workforceLoad,
    ];
    
    rows.push(row.join(","));
  });

  const csvContent = rows.join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  saveAs(blob, `${simulation.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.csv`);
}

/**
 * Export simulation metrics as a PDF report.
 */
export function exportToPdf(simulation: Simulation): void {
  const doc = new jsPDF();
  const title = `Simulation Report: ${simulation.name}`;
  
  // Header
  doc.setFontSize(18);
  doc.setTextColor(40, 40, 40);
  doc.text(title, 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by Reux Business Simulator | ${new Date().toLocaleDateString()}`, 14, 30);
  
  // Recommendation Summary (if comparison exists)
  let startY = 40;
  if (simulation.comparison && simulation.comparison.recommendationSummary) {
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.text("Reux Recommendation", 14, startY);
    
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    const splitText = doc.splitTextToSize(simulation.comparison.recommendationSummary, 180);
    doc.text(splitText, 14, startY + 6);
    
    startY += 10 + (splitText.length * 5);
  }

  // Summary Table
  const tableData = simulation.scenarios.map((s) => {
    const isRecommended = simulation.comparison?.recommendedId === s.id;
    return [
      isRecommended ? `* ${s.inputs.name}` : s.inputs.name,
      formatCurrency(s.summary.margin),
      formatPercent(s.summary.marginPct),
      `${s.summary.riskScore}/100`,
      formatPercent(s.summary.workforceLoad),
      `${s.summary.productivity} u/e/w`,
    ];
  });

  autoTable(doc, {
    startY,
    head: [["Scenario", "Weekly Margin", "Margin %", "Risk Score", "Workforce Load", "Productivity"]],
    body: tableData,
    theme: "grid",
    headStyles: { fillColor: [10, 10, 10], textColor: [255, 255, 255] },
    styles: { fontSize: 9 },
  });

  // Save the PDF
  doc.save(`${simulation.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.pdf`);
}
