import type { ScenarioInputs } from "./types";

// ─── Scenario Templates ─────────────────────────────────────────────────────
// Pre-built industry scenario templates for the Business Simulator.
// Each template provides a realistic baseline + 2 alternative scenarios
// so first-time visitors can see meaningful comparison results immediately.

export interface SimulationTemplate {
  id: string;
  name: string;
  industry: string;
  description: string;
  icon: string;
  color: string; // tailwind color prefix (e.g. "cyan", "violet")
  baseline: ScenarioInputs;
  scenarios: ScenarioInputs[];
}

export const SIMULATION_TEMPLATES: SimulationTemplate[] = [
  {
    id: "retail-holiday",
    name: "Holiday Season Staffing",
    industry: "Retail",
    description: "A mid-size retailer preparing for a 40% demand spike during the holiday season. Compare hiring temps vs overtime vs productivity training.",
    icon: "🛍️",
    color: "cyan",
    baseline: {
      name: "Current Staffing",
      employees: 80,
      avgHourlyCost: 22,
      weeklyDemand: 3000,
      productivityGainPct: 0,
      overtimeReductionPct: 0,
      supplierDelayRiskPct: 10,
      errorDefectRatePct: 3,
      forecastWeeks: 12,
    },
    scenarios: [
      {
        name: "Hire 20 Seasonal Workers",
        employees: 100,
        avgHourlyCost: 20,
        weeklyDemand: 4200,
        productivityGainPct: 0,
        overtimeReductionPct: 30,
        supplierDelayRiskPct: 12,
        errorDefectRatePct: 6,
        forecastWeeks: 12,
      },
      {
        name: "Max Overtime + Incentives",
        employees: 80,
        avgHourlyCost: 30,
        weeklyDemand: 4200,
        productivityGainPct: 8,
        overtimeReductionPct: 0,
        supplierDelayRiskPct: 18,
        errorDefectRatePct: 5,
        forecastWeeks: 12,
      },
    ],
  },
  {
    id: "saas-growth",
    name: "Engineering Team Scaling",
    industry: "SaaS",
    description: "A SaaS startup deciding whether to hire aggressively, outsource, or invest in automation to handle growing customer demand.",
    icon: "💻",
    color: "violet",
    baseline: {
      name: "Current Team",
      employees: 25,
      avgHourlyCost: 65,
      weeklyDemand: 500,
      productivityGainPct: 0,
      overtimeReductionPct: 0,
      supplierDelayRiskPct: 5,
      errorDefectRatePct: 4,
      forecastWeeks: 26,
    },
    scenarios: [
      {
        name: "Hire 8 Engineers",
        employees: 33,
        avgHourlyCost: 62,
        weeklyDemand: 750,
        productivityGainPct: 5,
        overtimeReductionPct: 40,
        supplierDelayRiskPct: 5,
        errorDefectRatePct: 6,
        forecastWeeks: 26,
      },
      {
        name: "Invest in Automation",
        employees: 25,
        avgHourlyCost: 68,
        weeklyDemand: 750,
        productivityGainPct: 30,
        overtimeReductionPct: 20,
        supplierDelayRiskPct: 3,
        errorDefectRatePct: 2,
        forecastWeeks: 26,
      },
    ],
  },
  {
    id: "logistics-disruption",
    name: "Supply Chain Disruption",
    industry: "Logistics",
    description: "A logistics company modeling responses to a major supplier disruption: diversify vendors, increase safety stock, or absorb the risk.",
    icon: "🚛",
    color: "amber",
    baseline: {
      name: "Normal Operations",
      employees: 120,
      avgHourlyCost: 26,
      weeklyDemand: 5000,
      productivityGainPct: 0,
      overtimeReductionPct: 0,
      supplierDelayRiskPct: 8,
      errorDefectRatePct: 2,
      forecastWeeks: 12,
    },
    scenarios: [
      {
        name: "Diversify Suppliers (+cost)",
        employees: 120,
        avgHourlyCost: 29,
        weeklyDemand: 5000,
        productivityGainPct: 3,
        overtimeReductionPct: 10,
        supplierDelayRiskPct: 3,
        errorDefectRatePct: 2,
        forecastWeeks: 12,
      },
      {
        name: "Absorb Risk (no change)",
        employees: 120,
        avgHourlyCost: 26,
        weeklyDemand: 5000,
        productivityGainPct: 0,
        overtimeReductionPct: 0,
        supplierDelayRiskPct: 35,
        errorDefectRatePct: 5,
        forecastWeeks: 12,
      },
    ],
  },
  {
    id: "manufacturing-lean",
    name: "Lean Manufacturing Transition",
    industry: "Manufacturing",
    description: "A factory evaluating a lean transformation: reduce headcount with automation vs train existing workers vs hybrid approach.",
    icon: "🏭",
    color: "emerald",
    baseline: {
      name: "Current Factory",
      employees: 200,
      avgHourlyCost: 24,
      weeklyDemand: 8000,
      productivityGainPct: 0,
      overtimeReductionPct: 0,
      supplierDelayRiskPct: 12,
      errorDefectRatePct: 6,
      forecastWeeks: 26,
    },
    scenarios: [
      {
        name: "Automation (-40 staff)",
        employees: 160,
        avgHourlyCost: 28,
        weeklyDemand: 8000,
        productivityGainPct: 25,
        overtimeReductionPct: 60,
        supplierDelayRiskPct: 8,
        errorDefectRatePct: 2,
        forecastWeeks: 26,
      },
      {
        name: "Training Program",
        employees: 200,
        avgHourlyCost: 26,
        weeklyDemand: 8000,
        productivityGainPct: 15,
        overtimeReductionPct: 30,
        supplierDelayRiskPct: 10,
        errorDefectRatePct: 3,
        forecastWeeks: 26,
      },
    ],
  },
  {
    id: "healthcare-staffing",
    name: "Clinic Staffing Model",
    industry: "Healthcare",
    description: "A multi-location clinic network deciding how to handle patient volume growth: hire nurses, extend hours, or open a new location.",
    icon: "🏥",
    color: "rose",
    baseline: {
      name: "Current Clinics",
      employees: 45,
      avgHourlyCost: 42,
      weeklyDemand: 900,
      productivityGainPct: 0,
      overtimeReductionPct: 0,
      supplierDelayRiskPct: 5,
      errorDefectRatePct: 1,
      forecastWeeks: 26,
    },
    scenarios: [
      {
        name: "Hire 10 Nurses",
        employees: 55,
        avgHourlyCost: 42,
        weeklyDemand: 1200,
        productivityGainPct: 5,
        overtimeReductionPct: 50,
        supplierDelayRiskPct: 5,
        errorDefectRatePct: 1,
        forecastWeeks: 26,
      },
      {
        name: "Extended Hours (OT)",
        employees: 45,
        avgHourlyCost: 52,
        weeklyDemand: 1200,
        productivityGainPct: 0,
        overtimeReductionPct: 0,
        supplierDelayRiskPct: 8,
        errorDefectRatePct: 3,
        forecastWeeks: 26,
      },
    ],
  },
];
