import type { ScenarioInputs } from "./types";

export interface SimulationTemplate {
  id: string;
  name: string;
  industry: string;
  description: string;
  icon: string;
  color: string;
  baseline: ScenarioInputs;
  scenarios: ScenarioInputs[];
}

const baseScenario = {
  averageOrderValue: 85,
  grossMarginPct: 42,
  forecastWeeks: 12,
};

export const SIMULATION_TEMPLATES: SimulationTemplate[] = [
  {
    id: "operations-decision",
    name: "Operations Decision",
    industry: "Operations",
    description: "Compare process changes, demand growth, quality issues, and staffing changes before committing.",
    icon: "Ops",
    color: "cyan",
    baseline: {
      ...baseScenario,
      name: "Current Operations",
      employees: 50,
      avgHourlyCost: 32,
      weeklyDemand: 1200,
      productivityGainPct: 8,
      overtimeReductionPct: 10,
      supplierDelayRiskPct: 12,
      errorDefectRatePct: 2.5,
    },
    scenarios: [
      {
        ...baseScenario,
        id: "process-improvement",
        name: "Process Improvement",
        description: "Higher productivity and lower overtime after workflow cleanup.",
        employees: 50,
        avgHourlyCost: 32,
        weeklyDemand: 1200,
        productivityGainPct: 12,
        overtimeReductionPct: 18,
        supplierDelayRiskPct: 12,
        errorDefectRatePct: 2.5,
      },
      {
        ...baseScenario,
        id: "demand-increase",
        name: "Demand Increase",
        description: "Higher demand with slightly higher supplier delay risk.",
        employees: 50,
        avgHourlyCost: 32,
        weeklyDemand: 1450,
        productivityGainPct: 8,
        overtimeReductionPct: 10,
        supplierDelayRiskPct: 15,
        errorDefectRatePct: 2.5,
      },
    ],
  },
  {
    id: "capacity-planning",
    name: "Capacity Planning",
    industry: "Capacity",
    description: "Compare staffing, demand, productivity, and quality tradeoffs before scaling an operation.",
    icon: "Cap",
    color: "violet",
    baseline: {
      name: "Current Capacity",
      employees: 42,
      avgHourlyCost: 36,
      weeklyDemand: 980,
      averageOrderValue: 110,
      grossMarginPct: 48,
      productivityGainPct: 5,
      overtimeReductionPct: 6,
      supplierDelayRiskPct: 10,
      errorDefectRatePct: 1.8,
      forecastWeeks: 16,
    },
    scenarios: [
      {
        id: "add-shift",
        name: "Add Shift",
        description: "Add capacity with more staff while reducing overtime pressure.",
        employees: 50,
        avgHourlyCost: 36,
        weeklyDemand: 1120,
        averageOrderValue: 110,
        grossMarginPct: 48,
        productivityGainPct: 5,
        overtimeReductionPct: 16,
        supplierDelayRiskPct: 10,
        errorDefectRatePct: 1.8,
        forecastWeeks: 16,
      },
      {
        id: "automation-assist",
        name: "Automation Assist",
        description: "Improve productivity without adding headcount.",
        employees: 42,
        avgHourlyCost: 36,
        weeklyDemand: 980,
        averageOrderValue: 110,
        grossMarginPct: 48,
        productivityGainPct: 14,
        overtimeReductionPct: 12,
        supplierDelayRiskPct: 10,
        errorDefectRatePct: 1.8,
        forecastWeeks: 16,
      },
    ],
  },
  {
    id: "staffing-plan",
    name: "Staffing Plan",
    industry: "Workforce",
    description: "Compare hiring, cross-training, automation, and lean coverage before changing the workforce plan.",
    icon: "Team",
    color: "emerald",
    baseline: {
      name: "Current Team",
      employees: 34,
      avgHourlyCost: 41,
      weeklyDemand: 760,
      averageOrderValue: 135,
      grossMarginPct: 46,
      productivityGainPct: 4,
      overtimeReductionPct: 5,
      supplierDelayRiskPct: 8,
      errorDefectRatePct: 1.6,
      forecastWeeks: 12,
    },
    scenarios: [
      {
        id: "hire-team",
        name: "Hire Team",
        description: "Add staff to cover demand while reducing overtime pressure.",
        employees: 40,
        avgHourlyCost: 41,
        weeklyDemand: 820,
        averageOrderValue: 135,
        grossMarginPct: 46,
        productivityGainPct: 4,
        overtimeReductionPct: 18,
        supplierDelayRiskPct: 8,
        errorDefectRatePct: 1.6,
        forecastWeeks: 12,
      },
      {
        id: "cross-train",
        name: "Cross Train",
        description: "Improve productivity with the existing team before adding headcount.",
        employees: 34,
        avgHourlyCost: 41,
        weeklyDemand: 760,
        averageOrderValue: 135,
        grossMarginPct: 46,
        productivityGainPct: 13,
        overtimeReductionPct: 11,
        supplierDelayRiskPct: 8,
        errorDefectRatePct: 1.6,
        forecastWeeks: 12,
      },
    ],
  },
  {
    id: "pricing-strategy",
    name: "Pricing Strategy",
    industry: "Pricing",
    description: "Compare price, demand, margin, and quality-risk tradeoffs before changing commercial strategy.",
    icon: "Price",
    color: "amber",
    baseline: {
      name: "Current Pricing",
      employees: 28,
      avgHourlyCost: 38,
      weeklyDemand: 920,
      averageOrderValue: 120,
      grossMarginPct: 44,
      productivityGainPct: 6,
      overtimeReductionPct: 8,
      supplierDelayRiskPct: 9,
      errorDefectRatePct: 1.8,
      forecastWeeks: 12,
    },
    scenarios: [
      {
        id: "premium-price",
        name: "Premium Price",
        description: "Raise price while modeling softer demand and a slightly higher service-risk burden.",
        employees: 28,
        avgHourlyCost: 38,
        weeklyDemand: 830,
        averageOrderValue: 136,
        grossMarginPct: 44,
        productivityGainPct: 6,
        overtimeReductionPct: 8,
        supplierDelayRiskPct: 11,
        errorDefectRatePct: 1.8,
        forecastWeeks: 12,
      },
      {
        id: "margin-protect",
        name: "Margin Protect",
        description: "Protect margin through cleaner process and quality controls.",
        employees: 28,
        avgHourlyCost: 38,
        weeklyDemand: 920,
        averageOrderValue: 120,
        grossMarginPct: 48,
        productivityGainPct: 11,
        overtimeReductionPct: 8,
        supplierDelayRiskPct: 9,
        errorDefectRatePct: 1.2,
        forecastWeeks: 12,
      },
    ],
  },
];
